tasks:
  - name: terraform
    init: |
      source /workspace/terraform-beginner-bootcamp-2023/bin/terraform
      source /workspace/terraform-beginner-bootcamp-2023/bin/create_credentials_trfc
      source /workspace/terraform-beginner-bootcamp-2023/bin/tf_alias
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      source /workspace/terraform-beginner-bootcamp-2023/bin/aws
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform