tasks:
  - name: terraform
    before: |
      source /workspace/terraform-beginner-bootcamp-2023/bin/terraform
      source /workspace/terraform-beginner-bootcamp-2023/bin/create_credentials_trfc
      source /workspace/terraform-beginner-bootcamp-2023/bin/tf_alias
      cp /workspace/terraform-beginner-bootcamp-2023/terraform.tfvars.example /workspace/terraform-beginner-bootcamp-2023/variables.tfvars
      source ~/.bash_profile
      nano /home/gitpod/.terraform.d/credentials.tfrc.json
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      source /workspace/terraform-beginner-bootcamp-2023/bin/aws
      source ~/.bash_profile
  - name: http-server
    before: |
      npm install --global http-server
    command: 
      http-server

vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform
